require('dotenv').config({ path: '../.env' });
const oracledb = require('oracledb');
const { getConnection, initDb, closeDb } = require('./db');

const dropTables = [
  'tickets',
  'bookings',
  'bus_seats',
  'train_seats',
  'flight_seats',
  'trips',
  'stations',
  'vehicles',
  'carriers',
  'users',
  'system_config'
];

const createTables = [
  // 1. users
  `CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    phone_number VARCHAR2(255),
    is_verified NUMBER(1) DEFAULT 0 CHECK (is_verified IN (0, 1)),
    password_reset_token VARCHAR2(255),
    password_reset_token_expiry TIMESTAMP,
    verification_otp VARCHAR2(255),
    otp_expiry TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,

  // 2. carriers
  `CREATE TABLE carriers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    contact_email VARCHAR2(255),
    contact_phone VARCHAR2(255),
    logo_url VARCHAR2(255),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
  )`,

  // 3. vehicles
  `CREATE TABLE vehicles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    vehicle_number VARCHAR2(255),
    transport_mode VARCHAR2(20) NOT NULL CHECK (transport_mode IN ('FLIGHT', 'TRAIN', 'BUS')),
    capacity NUMBER NOT NULL,
    seat_layout CLOB CHECK (seat_layout IS JSON),
    seat_classes CLOB CHECK (seat_classes IS JSON),
    total_seats NUMBER,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    carrier_id NUMBER NOT NULL,
    CONSTRAINT fk_vehicle_carrier FOREIGN KEY (carrier_id) REFERENCES carriers(id) ON DELETE CASCADE
  )`,

  // 4. stations
  `CREATE TABLE stations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    city VARCHAR2(255) NOT NULL,
    state VARCHAR2(255),
    country VARCHAR2(255) DEFAULT 'India',
    type VARCHAR2(30) NOT NULL CHECK (type IN ('AIRPORT', 'TRAIN_STATION', 'BUS_TERMINAL')),
    location MDSYS.SDO_GEOMETRY,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
  )`,

  // 5. trips
  `CREATE TABLE trips (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER NOT NULL,
    origin_station_id NUMBER NOT NULL,
    destination_station_id NUMBER NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    arrivalTime TIMESTAMP NOT NULL, -- Keep JavaScript matching naming conventions or Java property mapping (arrival_time)
    price NUMBER(10,2) NOT NULL,
    distance FLOAT NOT NULL,
    transport_mode VARCHAR2(20) NOT NULL CHECK (transport_mode IN ('FLIGHT', 'TRAIN', 'BUS')),
    available_seats NUMBER NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_trip_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_origin FOREIGN KEY (origin_station_id) REFERENCES stations(id),
    CONSTRAINT fk_trip_dest FOREIGN KEY (destination_station_id) REFERENCES stations(id)
  )`,

  // 6. bookings
  `CREATE TABLE bookings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    total_price NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING', 'PAYMENT_INITIATED', 'PAID', 'CANCELLED', 'REFUNDED')),
    stripe_session_id VARCHAR2(255),
    stripe_payment_intent_id VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,

  // 7. tickets
  `CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    trip_id NUMBER NOT NULL,
    passenger_name VARCHAR2(255) NOT NULL,
    passenger_email VARCHAR2(255),
    passenger_phone VARCHAR2(255),
    seat_number VARCHAR2(10),
    coach_number VARCHAR2(20),
    seat_class VARCHAR2(30),
    berth_type VARCHAR2(10),
    leg_price NUMBER(10,2) NOT NULL,
    qr_code CLOB,
    leg_order NUMBER,
    CONSTRAINT fk_ticket_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_ticket_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
  )`,

  // 8. system_config
  `CREATE TABLE system_config (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(255) NOT NULL UNIQUE,
    config_value VARCHAR2(255) NOT NULL,
    description VARCHAR2(255)
  )`,

  // 9. bus_seats
  `CREATE TABLE bus_seats (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    seat_no VARCHAR2(10) NOT NULL,
    row_no NUMBER NOT NULL,
    column_no VARCHAR2(5) NOT NULL,
    seat_type VARCHAR2(20),
    status VARCHAR2(15) DEFAULT 'AVAILABLE' NOT NULL CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED')),
    price NUMBER(10,2) NOT NULL,
    locked_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bus_seat_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
    CONSTRAINT uq_bus_seat_trip_seat UNIQUE (trip_id, seat_no)
  )`,

  // 10. train_seats
  `CREATE TABLE train_seats (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    coach_no VARCHAR2(10) NOT NULL,
    seat_no VARCHAR2(10) NOT NULL,
    berth_type VARCHAR2(5),
    seat_class VARCHAR2(20) NOT NULL,
    status VARCHAR2(15) DEFAULT 'AVAILABLE' NOT NULL CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED')),
    price NUMBER(10,2) NOT NULL,
    locked_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_train_seat_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
    CONSTRAINT uq_train_seat_trip_coach_seat UNIQUE (trip_id, coach_no, seat_no)
  )`,

  // 11. flight_seats
  `CREATE TABLE flight_seats (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    seat_no VARCHAR2(10) NOT NULL,
    row_no NUMBER NOT NULL,
    column_no VARCHAR2(5) NOT NULL,
    seat_class VARCHAR2(20) NOT NULL,
    status VARCHAR2(15) DEFAULT 'AVAILABLE' NOT NULL CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED')),
    price NUMBER(10,2) NOT NULL,
    locked_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_flight_seat_trip FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE,
    CONSTRAINT uq_flight_seat_trip_seat UNIQUE (trip_id, seat_no)
  )`
];

async function resetDb() {
  await initDb();
  const conn = await getConnection();

  console.log('Starting DB Clean...');
  for (const table of dropTables) {
    try {
      await conn.execute(`DROP TABLE ${table} CASCADE CONSTRAINTS`);
      console.log(`Dropped table: ${table}`);
    } catch (err) {
      if (err.errorNum === 942) {
        console.log(`Table ${table} did not exist, skipping drop.`);
      } else {
        console.error(`Error dropping table ${table}:`, err.message);
      }
    }
  }

  // Handle spatial metadata clean
  try {
    await conn.execute(`DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'STATIONS'`);
    console.log('Cleared USER_SDO_GEOM_METADATA entry for STATIONS');
  } catch (err) {
    console.warn('Could not clear USER_SDO_GEOM_METADATA:', err.message);
  }

  console.log('Recreating tables...');
  for (const sql of createTables) {
    try {
      await conn.execute(sql);
      // Extracts table name from CREATE TABLE <name>
      const tableName = sql.match(/CREATE TABLE (\w+)/i)[1];
      console.log(`Created table: ${tableName}`);
    } catch (err) {
      console.error(`Error executing SQL:`, sql);
      console.error(`Error details:`, err.message);
      await conn.close();
      await closeDb();
      process.exit(1);
    }
  }

  // Register spatial metadata and index
  try {
    await conn.execute(`
      INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
      VALUES ('STATIONS', 'LOCATION',
        MDSYS.SDO_DIM_ARRAY(
          MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.05),
          MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.05)
        ),
        4326
      )
    `);
    await conn.execute(`
      CREATE INDEX stations_spx ON stations(location) 
      INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
    `);
    console.log('Registered spatial metadata and index for STATIONS');
  } catch (err) {
    console.error('Error registering Oracle Spatial index:', err.message);
  }

  await conn.commit();
  await conn.close();
  await closeDb();
  console.log('DB Clean and initialization completed successfully.');
}

resetDb();
